# switch = {
#     '+': lambda x, y: x + y,    # 람다 표현식으로 실행할 코드를 작성
#     '*': lambda x, y: x * y
#     }
 
# x = '%'
# try:
#     print(switch[x](10, 20))    # 딕셔너리에 키를 지정하는 방식
# except KeyError:
#     print('default')

# class Person:
#     pass
# person = Person()
# a = 0
# print(isinstance(a, Person))

# class Person():
#     ''' 사람 클래스 '''
#     def __init__(self) -> None:
#         pass
#     def add(self, a, b):
#         ''' 더하는 함수 '''
#         pass
# a = 10
# print(globals())
# print(__name__)
# print(__file__)
# print(Person.__doc__)
# print(Person.add.__doc__)

